### ISSUE TITLE
Enhancement: Replace WiringPi with gpiod

### ISSUE THREAD

**Issue by mpapple-swift** [sbitxdev/sbitx#3]
WiringPi (https://github.com/WiringPi/WiringPi)is abandonware and must be replaced immediately.  The go-to replacement is gpiod (https://git.kernel.org/pub/scm/libs/libgpiod/libgpiod.git/).
@rafael2k has a solution @ https://github.com/Rhizomatica/sbitx-core/tree/gpiolib.

Quoting @rafael2k: "I re-wrote all the GPIO code using gpiolib here:
https://github.com/Rhizomatica/sbitx-core/tree/gpiolib

i2c is also done using libi2c and kernel-mode i2c bit-banging."

We should review @rafael2k's changes and incorporate a suitable replacement for WiringPi as soon as possible.

**Comment by rafael2k** [comment]
Btw, this is not libgpiod, but gpiolib:
https://github.com/raspberrypi/utils/tree/master/pinctrl

**Comment by mpapple-swift** [comment]
Thank you for the correction.

**Comment by rafael2k** [comment]
Replacing WiringPi is not a enhancement. WiringPi is now maintained, no need to replace it.
